Use Github Actions instead of Travis
Publishing the package to Hex through Travis failed with this error:

    $ rvm install 2.7

    $ rvm use $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl -v 2.0.5.4
    ERROR:  Error installing dpl:
            There are no versions of uri (~> 1.0.2) compatible with your Ruby & RubyGems. Maybe try installing an older version of the gem you're looking for?
            uri requires Ruby version >= 2.5. The current ruby version is 2.4.5.335.
    The command "rvm use $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl -v 2.0.5.4" failed and exited with 1 during .

Not sure that's worth fixing.  Let's switch to Github Actions.